#include "OpCodes.h"
#include "coral_show.h"

#include <iostream>
#include <string>
#include <unordered_map>

namespace ora {
    struct RawOp {
        int layer;
        int code;
        const char *mnemonic;
        const char *desc;
    };

    constexpr RawOp rawOps[] = {
        {1, 0, "KCOCOTCT", "Transaction Control"},
        {1, 1, "KTZFMT", "KTZ ForMaT block"},
        {1, 2, "KTZRDH", "Transaction Z Redo Data Header"},
        {1, 3, "KTZARC", "KTZ Allocate Record Callback"},
        {1, 4, "KTZREP", "KTZ REPlace record value"},
        {1, 5, "KTZURP", "KTZ Undo for RePlace"},
        {2, 0, "KCOCOTRD", "Transaction Read"},
        {3, 0, "KCOCOTUP", "Transaction Update"},
        {4, 0, "KCOCOTBK", "Transaction Block"},
        {4, 1, "KTBOPCLN", "Block cleanout opcode"},
        {4, 2, "KTBPHCLN", "physical cleanout opcode"},
        {4, 3, "KTBSARC", "single array change"},
        {4, 4, "KTBMARC", "Multiple changes to an array"},
        {4, 5, "KTBOPFMB", "format block"},
        {4, 6, "KTBOPBCC", "commit-time block cleanout opcode"},
        {4, 7, "KTBOPCLNL", "ITL cleanout callback"},
        {4, 8, "KTBOPBCCL", "Transaction Block Redo Block Commit Cleanout"},
        {5, 0, "KCOCOTUN", "Transaction Undo"},
        {5, 1, "KTURDB", "Undo block or undo segment header"},
        {5, 2, "KTURDH", "Update rollback segment header"},
        {5, 3, "KTURBG", "Rollout a transaction begin"},
        {5, 4, "KTURCM", "Commit transaction (transaction table update) - no undo record"},
        {5, 5, "KTUFMT", "Create rollback segment (format) - no undo record"},
        {5, 6, "KTUIRB", "Rollback record index in an undo block"},
        {5, 7, "KTUUBG", "Begin transaction (transaction table update)"},
        {5, 8, "KTURMR", "Mark transaction as dead"},
        {5, 9, "KTUUAE", "Undo routine to rollback the extend of a rollback segment"},
        {5, 10, "KTUREH", "Redo to perform the rollback of extend of rollback segment to the segment header."},
        {5, 11, "KTUBRB", "Rollback DBA in transaction table entry"},
        {5, 12, "KTURST", "Change transaction state (in transaction table entry)"},
        {5, 13, "KTURCT", "Convert rollback segment format (V6 -> V7)"},
        {5, 14, "KTURUC", "Change extent allocation parameters in a rollback segment"},
        {5, 15, "KTURCTS", "Undo Redo ConverT transaction table"},
        {5, 16, "KTURCTU", "KTU  Redo for ConverT to Unlimited extents format"},
        {
            5, 17, "KTURCTM",
            "KTU Redo  Convert for extent Move in extent map in unlimited format to segment header"
        },
        {5, 18, "KTURPX", "Transaction Undo segment Redo set Parent Xid"},
        {5, 19, "KTUTSL", "Transaction start audit log record"},
        {5, 20, "KTUTSC", "Transaction continue audit log record"},
        {5, 21, "KTURCVD", "Transaction Control Redo ConverT undo seg Down to 8.0 format"},
        {5, 22, "KTURPHC", "Transaction Redo PHysical Changes"},
        {5, 23, "KTURDBR", "Disable Block level Recovery"},
        {5, 24, "KTURLGU", "Kernel Transaction Undo Relog CHanGe"},
        {5, 25, "KTURJT", "Join sub Transaction"},
        {5, 26, "KTUUST", "Undo STopper undo callback"},
        {5, 27, "KTUSMFMT", "Transaction Control System Managed us Format"},
        {5, 28, "KTUUNTP", "Undo Need To Propagate"},
        {5, 29, "KTUBDB", "big undo"},
        {5, 30, "KTURCDTS", "change ondisk state for a distributed transaction"},
        {5, 31, "KTUFATTRC", "Flashback Archive Txn Table Redo Callback"},
        {5, 32, "KTUFATTRS", "Flashback Archive Txn Table Redo Set"},
        {5, 33, "KTUCHNF", "change notification commit marker"},
        {5, 34, "KTUQCNTTRC", "NTP bit for change notfn"},
        {5, 35, "KTUFACTTRS", "Flashback Archive Collect Txn Table Redo Set"},
        {6, 0, "KCOCODCF", "Control File"},
        {6, 1, "TBSCRDF", "TaBleSpace Remove DataFile"},
        {6, 2, "TBSCADF", "TaBleSpace Add DataFile"},
        {6, 3, "TBSCOFL", "TaBleSpace OFfLine"},
        {6, 4, "TBSCONL", "TaBleSpace ONLine"},
        {6, 5, "TBSCRDW", "TaBleSpace ReaD-Write"},
        {6, 6, "TBSCRDO", "TaBleSpace ReaD-Only"},
        {6, 7, "TBSCRTS", "TaBleSpace Remove TableSpace"},
        {6, 8, "TBSCATS", "TaBleSpace Add TableSpace"},
        {6, 9, "TBSCUTP", "TaBleSpace Undo TsPitr"},
        {6, 10, "TBSCUCV", "TaBleSpace undo plugged datafile convert"},
        {6, 11, "TBSCREN", "Tablespace Undo Rename"},
        {10, 0, "KCOCODIX", "INDEX"},
        {10, 1, "KDICPDO", "load index block (Loader with direct mode)"},
        {10, 2, "KDICLIN", "Insert leaf row"},
        {10, 3, "KDICLPU", "Purge leaf row"},
        {10, 4, "KDICLDE", "Mark leaf row deleted"},
        {10, 5, "KDICLRE", "Restore leaf row (clear leaf delete flags)"},
        {10, 6, "KDICLOK", "Lock index block"},
        {10, 7, "KDICULO", "Unlock index block"},
        {10, 8, "KDICLNE", "Initialize new leaf block"},
        {10, 9, "KDICAIR", "Apply Itl Redo"},
        {10, 10, "KDICLNX", "Set leaf block next link"},
        {10, 11, "KDICLPR", "Set leaf block previous link"},
        {10, 12, "KDICRSP", "Init root block after split"},
        {10, 13, "KDICLEM", "Make leaf block empty"},
        {10, 14, "KDICIMA", "Restore block before image"},
        {10, 15, "KDICBIN", "Branch block row insert"},
        {10, 16, "KDICBPU", "Branch block row purge"},
        {10, 17, "KDICBNE", "Initialize new branch block"},
        {10, 18, "KDICLUP", "Update keydata in row"},
        {10, 19, "KDICLCL", "Clear row's split flag"},
        {10, 20, "KDICLSE", "Set row's split flag"},
        {10, 21, "KDICUGE", "General undo above the cache (undo)"},
        {10, 22, "KDICULK", "Undo operation on leaf key above the cache (undo)"},
        {10, 23, "KDICREB", "Restore block to b-tree"},
        {10, 24, "KDICSIT", "Shrink ITL (transaction entries)"},
        {10, 25, "KDICFRB", "Format root block redo"},
        {10, 26, "KDICUFB", "Undo of format root block (undo)"},
        {10, 27, "KDICUFR", "Redo for undo of format root block"},
        {10, 28, "KDICUMG", "Undo for migrating block"},
        {10, 29, "KDICMG", "Redo for migrating block"},
        {10, 30, "KDICLNU", "IOT leaf block nonkey update"},
        {10, 31, "KDICDLR", "Direct load root redo"},
        {10, 32, "KDICCOM", "Combine operation for insert and restore rows"},
        {10, 33, "KDICTIX", "Temp index redo apply"},
        {10, 34, "KDICFRE", "Remove block from b-tree and empty block"},
        {10, 35, "KDICLCU", ""},
        {10, 36, "KDICLMN", "Supplemental logging"},
        {10, 37, "KDICULN", "Undo of non-key updates"},
        {10, 38, "KDICICU", "Logical non-key update"},
        {10, 39, "KDICBUR", "Branch update range"},
        {10, 40, "KDICBDU", "Branch DBA update"},
        {11, 0, "KCOCODRW", "Row Access"},
        {11, 1, "KDOIUR", "Interpret Undo Record (Undo)"},
        {11, 2, "KDOIRP", "Insert Row Piece"},
        {11, 3, "KDODRP", "Drop Row Piece"},
        {11, 4, "KDOLKR", "Lock Row Piece"},
        {11, 5, "KDOURP", "Update Row Piece"},
        {11, 6, "KDOORP", "Overwrite Row Piece"},
        {11, 7, "KDOMFC", "Manipulate First Column (add or delete the 1st column)"},
        {11, 8, "KDOCFA", "Change Forwarding address"},
        {11, 9, "KDOCKI", "Change the Cluster Key Index"},
        {11, 10, "KDOSKL", "Set Key Links Change the forward & backward key links on a cluster key"},
        {11, 11, "KDOQMI", "Quick Multi-Insert (ex insert as select ...)"},
        {11, 12, "KDOQMD", "Quick Multi-Delete"},
        {11, 13, "KDOTBF", "Toggle Block Header flags"},
        {11, 14, "KDODSC", ""},
        {11, 15, "KDOMBC", ""},
        {11, 16, "KDOLMN", "Logminer support RM for rowpiece with only logminer columns-"},
        {11, 17, "KDOLLB", "Logminer support RM for LOB id key information -"},
        {11, 18, "KDOLBE", "Logminer support RM for LOB operation errors"},
        {11, 19, "KDOURA", "Logminer support - array updates"},
        {11, 20, "KDOSHK", "Logminer support"},
        {11, 21, "KDOURP2", "Logminer support"},
        {11, 22, "KDOCMP", "Logminer support"},
        {11, 23, "KDODCU", "Logminer support"},
        {11, 24, "KDOMRK", "Logminer support"},
        {11, 25, "KDOAIR", "Logminer support"},
        {12, 0, "KCOCODCL", "Cluster"},
        {13, 0, "KCOCOTSG", "Transaction Segment"},
        {13, 1, "KTSDSF", "Data Segment Format"},
        {13, 2, "KTSFFB", "format free list block"},
        {13, 3, "KTSRCTU", "redo for convert to unlimited extents format"},
        {13, 4, "KTSRFSH", "fix segment header by moving its extent to ext 0"},
        {13, 5, "KTSFRBFMT", "format data block"},
        {13, 6, "KTSFRBLNK", "set link value on block"},
        {13, 7, "KTSFRGRP", "freelist related fgroup/segheader redo"},
        {13, 8, "KTSFUGRP", "freelist related fgroup/segheader undo"},
        {13, 9, "KTSFUNLK", "undo for linking block to xnt freelist"},
        {13, 10, "KTSBSFO", "BITMAP - format segment header"},
        {13, 11, "KTSBBFO", "BITMAP - format bitmap block"},
        {13, 12, "KTSBIFO", "BITMAP - format bitmap index block"},
        {13, 13, "KTSBBREDO", "BITMAP - redo for bmb"},
        {13, 14, "KTSBBUNDO", "BITMAP - undo for BMB"},
        {13, 15, "KTSBIREDO", "BITMAP - redo for index map"},
        {13, 16, "KTSBIUNDO", "BITMAP - undo for index map"},
        {13, 17, "KTSPHFO", "Bitmap Seg - format segment Header"},
        {13, 18, "KTSPFFO", "Bitmap Seg - format First level bitmap block"},
        {13, 19, "KTSPSFO", "Bitmap Seg - format Second level bitmap block"},
        {13, 20, "KTSPTFO", "Bitmap Seg - format Third level bitmap block"},
        {13, 21, "KTSPBFO", "Bitmap Seg - format data block"},
        {13, 22, "KTSPFREDO", "Bitmap Seg - Redo for L1 bmb -"},
        {13, 23, "KTSPFUNDO", "Bitmap Seg - Undo for L1 BMB -"},
        {13, 24, "KTSPSREDO", "Bitmap Seg - Redo for L2 bmb -"},
        {13, 25, "KTSPSUNDO", "Bitmap Seg - Undo for L2 BMB -"},
        {13, 26, "KTSPTREDO", "Bitmap Seg - Redo for L3 bmb -"},
        {13, 27, "KTSPTUNDO", "Bitmap Seg - Undo for L3 BMB -"},
        {13, 28, "KTSPHREDO", "Bitmap Seg - Redo for pagetable segment header block -"},
        {13, 29, "KTSPHUNDO", "Bitmap Seg - Undo for pagetable segment header block -"},
        {13, 30, "KTSPLBFFO", "Bitmap Seg - format L1 BMB for LOB segments"},
        {13, 31, "KTSKFREDO", "Bitmap Seg - Shrink redo for L1 -"},
        {13, 32, "KTSKHREDO", "Bitmap Seg - Shrink redo for segment header -"},
        {13, 33, "KTSKEREDO", "Bitmap Seg - Shrink redo for extent map blk -"},
        {13, 34, "KTSKHUNDO", "Bitmap Seg - Shrink undo for segment header -"},
        {13, 35, "KTSKFUNDO", "Bitmap Seg - Shrink undo for L1 -"},
        {13, 36, "KTSKSREDO", "Bitmap Seg shrink related"},
        {13, 37, "KTSKSUNDO", "Bitmap Seg shrink related"},
        {13, 38, "KTSKTREDO", "Bitmap Seg shrink related"},
        {13, 39, "KTSKTUNDO", "Bitmap Seg shrink related"},
        {13, 40, "KTSKEUNDO", "Bitmap Seg - Shrink redo for extent map blk -"},
        {13, 41, "KTSLEFREDO", "NGLOB format opcode Extent Header"},
        {13, 42, "KTSLPFREDO", "NGLOB format opcode Persistent Undo"},
        {13, 43, "KTSLHFREDO", "NGLOB format opcode Hash bucket"},
        {13, 44, "KTSLFFREDO", "NGLOB format opcode Free SPace"},
        {13, 45, "KTSLSFREDO", "NGLOB format opcode Segment Header"},
        {13, 46, "KTSLBFREDO", "NGLOB format opcode data block"},
        {13, 47, "KTSLEUREDO", "NGLOB block update Extent Header redo"},
        {13, 48, "KTSLEUUNDO", "NGLOB block update Extent Header undo"},
        {13, 49, "KTSLHUREDO", "NGLOB block update Hash Bucket redo"},
        {13, 50, "KTSLHUUNDO", "NGLOB block update Hash Bucket undo"},
        {13, 51, "KTSLFUREDO", "NGLOB block update Free Space redo"},
        {13, 52, "KTSLFUUNDO", "NGLOB block update Free Space undo"},
        {13, 53, "KTSLPUREDO", "NGLOB block update Persistent Undo redo"},
        {13, 54, "KTSLPUUNDO", "NGLOB block update Persistent Undo undo"},
        {13, 55, "KTSLSUREDO", "NGLOB block update Segment Header redo"},
        {13, 56, "KTSLSUUNDO", "NGLOB block update Segment Header undo"},
        {14, 0, "KCOCOTEX", "Transaction Extent"},
        {14, 1, "KTECUSH", "Unlock Segment Header"},
        {14, 2, "KTECRLK", "Redo set extent map disk LocK"},
        {14, 3, "KTEFRCU", "redo for conversion to unlimited format"},
        {14, 4, "KTEOPEMREDO", "extent operation redo"},
        {14, 5, "KTEOPEUNDO", "extent operation undo"},
        {14, 6, "KTEOPEFREDO", "extent map format redo"},
        {14, 7, "KTECNV", "redo"},
        {14, 8, "KTEOPUTRN", "undo for truncate ops, flush the object"},
        {14, 9, "KTEFUCTL", "undo for reformat of a ctl block"},
        {14, 10, "KTEFRCTL", "redo to facilitate above undo"},
        {14, 11, "KTECRCLN", "redo to clean xids in seghdr/fgb"},
        {14, 12, "KTEOPRPECT", "SMU-Retention Redo to propagate extent commit time"},
        {15, 0, "KCOCOTTS", "Table Space"},
        {15, 1, "KTTFSU", "format save undo header"},
        {15, 2, "KTTSUN", "add save undo record"},
        {15, 3, "KTTNBK", "move to next block"},
        {15, 4, "KTTNAS", "point to next save undo record"},
        {15, 5, "KTTUSB", "update saveundo blk during save undo application"},
        {16, 0, "KCOCOQRC", "Row Cache"},
        {17, 0, "KCOCORCV", "Recovery (REDO)"},
        {
            17, 1, "KCVOPEHB",
            "End Hot Backup. This operation clears the hot backup in-progress flags in the indicated list of files"
        },
        {
            17, 2, "KCVOPENT",
            "ENable Thread This operation creates a redo record signalling that a thread has been enabled"
        },
        {17, 3, "KCVOPCRM", "Crash Recovery Marker"},
        {17, 4, "KCVOPRSZ", "ReSiZeable datafiles"},
        {17, 5, "KCVOPONL", "tablespace ONline"},
        {17, 6, "KCVOPOFF", "tablespace OFFline"},
        {17, 7, "KCVOPRDW", "tablespace ReaD Write"},
        {17, 8, "KCVOPRDO", "tablespace ReaD Only"},
        {17, 9, "KCVOPADD", "ADDing datafiles to database"},
        {17, 10, "KCVOPDRP", "tablespace DRoP"},
        {17, 11, "KCVOPTPR", "Tablespace PitR"},
        {17, 12, "KCVOPPLG_PRE10GR2", "PLUgging datafiles to database"},
        {17, 13, "KCVOPCNV", "convert plugged in datafiles"},
        {17, 14, "KCVOPADF_PRE10GR2", "ADding dataFiles to database"},
        {17, 15, "KCVOPHBR", "heart-beat redo"},
        {17, 16, "KCVOPTRN", "tablespace rename"},
        {17, 17, "KCVOPENT_10GR2", "ENable Thread"},
        {17, 18, "KCVOPONL_10GR2", "tablespace ONline"},
        {17, 19, "KCVOPOFF_10GR2", "tablespace OFFline"},
        {17, 20, "KCVOPRDW_10GR2", "tablespace ReaD Write"},
        {17, 21, "KCVOPRDO_10GR2", "tablespace ReaD Only"},
        {17, 22, "KCVOPPLG_10GR2", "PLUgging datafiles to db"},
        {17, 23, "KCVOPADF_10GR2", "ADding dataFiles to database"},
        {17, 24, "KCVOPCNV_10GR2", "convert plugged in datafiles"},
        {17, 25, "KCVOPTPR_10GR2", "Tablespace PitR"},
        {17, 26, "KCVOPFDP", "for file drop in tablespace"},
        {17, 27, "KCVOPIEN", "for internal thread enable"},
        {17, 28, "KCVOPMFL", "readable standby metadata flush"},
        {17, 29, "KCVOPDBK", "database key creation (after bumping compatible to 11g)"},
        {17, 30, "KCVOPADF", "ADding dataFiles to database"},
        {17, 31, "KCVOPPLG", "PLUgging datafiles to db"},
        {17, 32, "KCVOPSPHUPD", "for modifying space header info"},
        {17, 33, "KCVOPTMR", "TSE Masterkey Rekey"},
        {18, 0, "KCOCOHLB", "Hot Backup Log Blocks"},
        {18, 1, "KCBKCOLB", "Log block image"},
        {18, 2, "KCBKCORV", "Recovery testing"},
        {18, 3, "KCBKCOREU", "Object/Range reuse"},
        {19, 0, "KCOCODLB", "Direct Loader Log Blocks"},
        {19, 1, "KCBLCOLB", "Direct block logging"},
        {19, 2, "KCBLCOIR", "Invalidate range"},
        {19, 3, "KCBLCRLB", "Direct block relogging"},
        {19, 4, "KCBLCRIR", "Invalidate range relogging"},
        {20, 0, "KCOCOKCK", "Compatibility Segment operations"},
        {20, 1, "KCKFCS", "Format compatibility segment"},
        {20, 2, "KCKUCS", "Update compatibility segment"},
        {20, 3, "KCKURD", "Update Root Dba in controlfile and file header 1"},
        {20, 4, "KCK_INV_SQL_SIG", "Set bit in a SQL Tuning Existence Bit Vector"},
        {20, 5, "KCK_INV_SQL_SIG", "Invalidate an SQL Statement by Signature"},
        {20, 6, "KCK_UNAUTH_CUR", "Unauthorize cursors after sys privilege revoke"},
        {21, 0, "KCOCOLFS", "LOB segment operations"},
        {21, 1, "KDLOPWRI", "Write data into ILOB data block"},
        {22, 0, "KCOCOTBF", "Tablespace bitmapped file operations"},
        {22, 1, "KTFBHFO", "format space header"},
        {22, 2, "KTFBHREDO", "space header generic redo"},
        {22, 3, "KTFBHUNDO", "space header undo"},
        {22, 4, "KTFBBFO", "space bitmap block format"},
        {22, 5, "KTFBBREDO", "bitmap block generic redo"},
        {23, 0, "KCOCOLWR", "write behind logging of blocks"},
        {23, 1, "KCBBLWR", "Dummy block written callback"},
        {23, 2, "KCBBLRD", "log reads"},
        {23, 3, "KCBBLDWR", "log DirectWrites"},
        {24, 0, "KCOCOKRV", "Logminer related (DDL or OBJV# redo)"},
        {24, 1, "KRVDDL", "common portion of the ddl"},
        {24, 2, "KRVDLR", "direct load redo"},
        {24, 3, "KRVLOB", "lob related info"},
        {24, 4, "KRVMISC", "misc info"},
        {24, 5, "KRVUSER", "user info"},
        {24, 6, "KRVDLR10", "direct load redo 10i"},
        {24, 7, "KRVUOP", "logminer undo opcode"},
        {24, 8, "KRVXML", "xmlredo - doc or dif - opcode"},
        {24, 9, "KRVPLSQL", "PL/SQL redo"},
        {24, 10, "KRVURU", "Uniform Redo Unchained"},
        {24, 11, "KRVCMT", "txn commit marker"},
        {24, 12, "KRVCFF", "supplog marker"},
        {25, 0, "KCOCOQUE", "Queue Related"},
        {25, 1, "KDQSUN", "undo"},
        {25, 2, "KDQSIN", "init"},
        {25, 3, "KDQSEN", "enqueue"},
        {25, 4, "KDQSUP", "update"},
        {25, 5, "KDQSDL", "delete"},
        {25, 6, "KDQSLK", "lock"},
        {25, 7, "KDQSMM", "min/max"},
        {26, 0, "KCOCOLOB", "Local LOB Related"},
        {26, 1, "KDLIRUNDO", "generic lob undo"},
        {26, 2, "KDLIRREDO", "generic lob redo"},
        {26, 3, "KDLIRFRMT", "lob block format redo"},
        {26, 4, "KDLIRINVL", "lob invalidation redo"},
        {26, 5, "KDLIRLOAD", "lob cache-load redo"},
        {26, 6, "KDLIRBIMG", "direct lob direct-load redo"},
        {26, 7, "KDLIRCALI", "dummy calibration redo"},
        {27, 0, "KCOCOBCT", "Block Change Tracking"},
        {27, 1, "KRCPBSW", "op-code for bitmap switch"}
    };

    static const std::unordered_map<int, std::unordered_map<int, std::string>> codeMap
    = [] {
        std::unordered_map<int, std::string> headers;

        for (const auto& op : rawOps) {
            if (op.code == 0) headers[op.layer] = op.desc;
        }

        std::unordered_map<int, std::unordered_map<int, std::string>> out;

        for (const auto& op : rawOps) {
            if (op.code != 0) {
                out[op.layer][op.code] = fmt::format("{}.{} ({}) {}: {}",
                    op.layer, op.code, op.mnemonic, headers[op.layer], op.desc);
            }
        }

        return out;
    }();

    std::string opCode_string(const uint8_t layer, const uint8_t code) {

        const auto layerIt = codeMap.find(layer);
        if (layerIt == codeMap.end()) {
            return fmt::format("{}.{} Unknown layer", layer, code);
        }

        const auto codeIt = layerIt->second.find(code);
        if (codeIt == layerIt->second.end()) {
            return fmt::format("{}.{} Unknown code", layer, code);
        }
        return codeIt->second;
    }
}

namespace OpCodes {
    int main() {
        std::cout << ora::opCode_string(5, 1) << "\n";
        std::cout << ora::opCode_string(11, 2) << "\n";
        std::cout << ora::opCode_string(99, 1) << "\n"; // 없는 layer 테스트
        std::cout << ora::opCode_string(5, 99) << "\n"; // 없는 code 테스트
        return 0;
    }
}
